# (string) Title of your wiki
title: 42 wiki
demo_ver: 1.0.1
remote_theme: Drassil/git-wiki-theme@865e801
description: π–¥ 42cursus κ³µλ¶€ λ…ΈνΈ
show_downloads: false
show_wiki_pages: true
show_wiki_pages_limit: 40
paginate: 5
paginate_path: "assets/blog/page:num"
blog_feature: true
show_wiki_posts: true
show_wiki_posts_limit: 5
logo_url: assets/images/42wiki.png
google_analytics:
git_branch: master
use_github_wiki: false
use_prose_io: false
service: github
search_engine : "js"
#google_cse_token: 007197903287787072094:8rbvkeqo6qw
wiki_folder : "wiki"
permalink: /blog/posts/:year/:month/:day/:title:output_ext
site_root: 
markdown: kramdown
highlighter: rouge
kramdown:
        input: GFM
        syntax_highlighter: rouge

languages: ['ko','en']
default_lang: "ko"
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false

url: https://yeosong1.github.io
baseurl: /


#
# Jekyll
#

defaults:
 - 
    scope:
      path: "wiki"
    values:
      permalink: /:basename
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "git-wiki-post"
 -
    scope:
      path: assets/blog
    values:
      layout: "git-wiki-blog"

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-polyglot
 - jekyll-paginate
 - jekyll-glisti
# - jekyll-coffeescript
# - jekyll-default-layout
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-remote-theme
# - jekyll-relative-links 
# - jekyll-titles-from-headings
# - jekyll-sitemap

  
#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_after_content: "drassil/comments.html"
inc_after_head : "drassil/head.html"
inc_before_page_list : "drassil/sidebar.html"
